### ISSUE TITLE
Some Mistakes in Source code

### ISSUE THREAD

**Issue by meishijia** [oxydrain/AudioSlicer#1]
Hi, I'm working with audio slicing recently. I always tried to use amplitude to slice the audio. Your idea is wonderful that energy is be used to slice audio. However, there are some mistakes made me a little confused.
There is a function naming `GetTime()` but not defined and a variable `cut_samples` be used before definition.
It is very kind of you to check it again, and it would help me a lot. Thank you!

**Comment by oxydrain** [comment]
Hello Andra!

I've made the changes for this code to work and it's functional now (:  
Two utilities functions were missing, the cut_times were referenced before it was called, and there was a problem to generate the json file. 

Thanks for pointing out the problems with it!
I'm glad i could help. o/
